Fixes

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,36 +1,54 @@
 #!/usr/bin/env bash
-# Configures web-02 to be identical to web-01 server
+# Install and configure Nginx with specific settings:
+# - Listens on port 80.
+# - Returns a page containing "Holberton School" when queried at the root with a curl GET request.
+# - Configures /redirect_me as a "301 Moved Permanently".
+# - Includes a custom 404 page containing "Ceci n'est pas une page".
+# - Contains a custom HTTP header named X-Served-By with the value being the hostname of the running server.
 
-sudo apt-get -y upgrade
+# Update package information
+sudo apt-get update
 
-sudo apt-get -y install nginx
+# Install Nginx
+sudo apt-get install -y nginx
 
-sudo mkdir /etc/nginx/html
-sudo touch /etc/nginx/html/index.html
+# Create HTML directory and files
+sudo mkdir -p /var/www/html
+sudo tee /var/www/html/index.html > /dev/null <<EOL
+Hello World!
+EOL
 
-echo "Hello World!" | sudo tee /etc/nginx/html/index.html
+sudo tee /var/www/html/404.html > /dev/null <<EOL
+Ceci n'est pas une page
+EOL
 
-cat <<EOF | sudo tee /etc/nginx/sites-available/default
+# Configure Nginx default site
+sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
 server {
-     listen 80;
-     listen [::]:80;
-     server_name _;
-     add_header X-Served-By "$HOSTNAME";
-     root /etc/nginx/html;
-     index index.html index.htm;
+    listen 80 default_server;
+    listen [::]:80 default_server;
+    add_header X-Served-By \$hostname;
+    root   /var/www/html;
+    index  index.html index.htm;
 
-     location /redirect_me {
-       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-     }
+    location /redirect_me {
+        return 301 http://cuberule.com/;
+    }
 
-     error_page 404 /404.html;
-     location /404 {
-        root /etc/nginx/html;
+    error_page 404 /404.html;
+    location = /404.html {
+        root /var/www/html;
         internal;
-     }
+    }
 }
-EOF
+EOL
 
-echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
-
+# Restart Nginx service
 sudo service nginx restart
+
+# Check if Nginx restarted successfully
+if [ $? -eq 0 ]; then
+    echo "Nginx restarted successfully."
+else
+    echo "Failed to restart Nginx. Check the configuration."
+fi
